include "../src//SDK/MessageBody.dfy"
module MessageBodyUnitTests {
import MessageBody
import StandardLibrary
import StandardLibrary.UInt
import StandardLibrary.String
import Wrappers
import SerializableTypes
import UTF8
import Sets
import Seq
import Math
import AESEncryption
import RSAEncryption
import HMAC
import Signature
import Base64
import Defaults
import AwsKmsArnParsing
import Actions
import Constants
import AwsKmsUtils
import AwsKmsMrkAreUnique
import AwsKmsMrkMatchForDecrypt
import Random
import ExternRandom
import Streams
import Frames
import SerializeFunctions
import Header
import EncryptionContext
import V1HeaderBody
import HeaderTypes
import SharedHeaderFunctions
import EncryptedDataKeys
import V2HeaderBody
import HeaderAuth
import Aws
import Aws.Crypto
import Com
import Com.Amazonaws
import Com.Amazonaws.Kms
import MaterialProviders
import MaterialProviders.Client
import MaterialProviders.AlgorithmSuites
import MaterialProviders.DefaultClientSupplier
import MaterialProviders.DefaultCMM
import MaterialProviders.Materials
import MaterialProviders.CMM
import MaterialProviders.Commitment
import MaterialProviders.AwsKmsDiscoveryKeyring
import MaterialProviders.Keyring
import MaterialProviders.AwsKmsMrkKeyring
import MaterialProviders.AwsKmsMrkDiscoveryKeyring
import MaterialProviders.AwsKmsKeyring
import MaterialProviders.MultiKeyring
import MaterialProviders.RawAESKeyring
import MaterialProviders.RawRSAKeyring
method {:test} test0() {
var d0 : seq<Frames.RegularFrame> := [];
var r0 := MessageBody.WriteMessageRegularFrames(d0);
expect if |d0| == 0 then r0 == [] else r0 == MessageBody.WriteMessageRegularFrames(Seq.DropLast(d0)) + Frames.WriteRegularFrame(Seq.Last(d0));
}
method {:test} test1() {
var d0 : seq<StandardLibrary.UInt.uint8> := [];
var d1 : MessageBody.BodyAADContent := MessageBody.BodyAADContent.AADRegularFrame;
var r0 := MessageBody.BodyAAD(d0, d1, (200605721 as StandardLibrary.UInt.uint32), (5620492334958379030 as StandardLibrary.UInt.uint64));
}
method {:test} test2() {
var d0 : HeaderTypes.MessageType := HeaderTypes.MessageType.TYPE_CUSTOMER_AED;
var d1 : HeaderTypes.MessageId := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d2 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d3 : UTF8.ValidUTF8Bytes := [];
var d4 : seq<StandardLibrary.UInt.uint8> := [];
var d5 : seq<StandardLibrary.UInt.uint8> := [];
var d6 : SerializableTypes.ESDKEncryptedDataKey := Aws.Crypto.EncryptedDataKey.EncryptedDataKey(keyProviderId:=d3,keyProviderInfo:=d4,ciphertext:=d5);
var d7 : SerializableTypes.ESDKEncryptedDataKeys := [d6];
var d8 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d9 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V1HeaderBody(messageType:=d0,esdkSuiteId:=61148,messageId:=d1,encryptionContext:=d2,encryptedDataKeys:=d7,contentType:=d8,headerIvLength:=3504,frameLength:=1649);
var d10 : seq<StandardLibrary.UInt.uint8> := [];
var d11 : SerializableTypes.ESDKEncryptionContext := map[];
var d12 : Aws.Crypto.AlgorithmSuiteId := Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d13 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=32,tagLength:=16,ivLength:=12);
var d14 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d15 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.None;
var d16 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d17 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=35,id:=d12,encrypt:=d13,kdf:=d14,commitment:=d15,signature:=d16);
var d18 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d19 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d20 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d18,headerAuthTag:=d19);
var d21 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d9,rawHeader:=d10,encryptionContext:=d11,suite:=d17,headerAuth:=d20);
var d22 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d23 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d24 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d25 : Frames.Frame := Frames.Frame.NonFramed(header:=d21,iv:=d22,encContent:=d23,authTag:=d24);
var r0 := MessageBody.BodyAADByFrameType(d25);
}
method {:test} test3() {
var d0 : HeaderTypes.MessageType := HeaderTypes.MessageType.TYPE_CUSTOMER_AED;
var d1 : HeaderTypes.MessageId := [0, 0, 0, 0, 0, 0, 0, 0, 0];
var d2 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d3 : UTF8.ValidUTF8Bytes := [];
var d4 : seq<StandardLibrary.UInt.uint8> := [];
var d5 : seq<StandardLibrary.UInt.uint8> := [];
var d6 : SerializableTypes.ESDKEncryptedDataKey := Aws.Crypto.EncryptedDataKey.EncryptedDataKey(keyProviderId:=d3,keyProviderInfo:=d4,ciphertext:=d5);
var d7 : SerializableTypes.ESDKEncryptedDataKeys := [d6];
var d8 : HeaderTypes.ContentType := HeaderTypes.ContentType.Framed;
var d9 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V1HeaderBody(messageType:=d0,esdkSuiteId:=3504,messageId:=d1,encryptionContext:=d2,encryptedDataKeys:=d7,contentType:=d8,headerIvLength:=2278,frameLength:=4294957893);
var d10 : seq<StandardLibrary.UInt.uint8> := [];
var d11 : SerializableTypes.ESDKEncryptionContext := map[];
var d12 : Aws.Crypto.AlgorithmSuiteId := Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d13 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=32,tagLength:=16,ivLength:=12);
var d14 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d15 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.None;
var d16 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d17 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=37,id:=d12,encrypt:=d13,kdf:=d14,commitment:=d15,signature:=d16);
var d18 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d19 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d20 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d18,headerAuthTag:=d19);
var d21 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d9,rawHeader:=d10,encryptionContext:=d11,suite:=d17,headerAuth:=d20);
var d22 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d23 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d24 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d25 : Frames.Frame := Frames.Frame.FinalFrame(header:=d21,seqNum:=582,iv:=d22,encContent:=d23,authTag:=d24);
var r0 := MessageBody.BodyAADByFrameType(d25);
}
method {:test} test4() {
var d0 : HeaderTypes.MessageType := HeaderTypes.MessageType.TYPE_CUSTOMER_AED;
var d1 : HeaderTypes.MessageId := [0, 0, 0, 0, 0, 0, 0];
var d2 : UTF8.ValidUTF8Bytes := [];
var d3 : UTF8.ValidUTF8Bytes := [];
var d4 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d2,value:=d3);
var d5 : UTF8.ValidUTF8Bytes := [];
var d6 : UTF8.ValidUTF8Bytes := [];
var d7 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d5,value:=d6);
var d8 : UTF8.ValidUTF8Bytes := [];
var d9 : UTF8.ValidUTF8Bytes := [];
var d10 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d8,value:=d9);
var d11 : UTF8.ValidUTF8Bytes := [];
var d12 : UTF8.ValidUTF8Bytes := [];
var d13 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d11,value:=d12);
var d14 : UTF8.ValidUTF8Bytes := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d15 : UTF8.ValidUTF8Bytes := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d16 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d14,value:=d15);
var d17 : UTF8.ValidUTF8Bytes := [194, 152, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d18 : UTF8.ValidUTF8Bytes := [201, 171, 0, 0, 0, 0, 0, 0];
var d19 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d17,value:=d18);
var d20 : UTF8.ValidUTF8Bytes := [218, 128, 0, 0, 0];
var d21 : UTF8.ValidUTF8Bytes := [222, 187, 0, 0, 0];
var d22 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d20,value:=d21);
var d23 : UTF8.ValidUTF8Bytes := [207, 173];
var d24 : UTF8.ValidUTF8Bytes := [199, 176];
var d25 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d23,value:=d24);
var d26 : EncryptionContext.ESDKCanonicalEncryptionContext := [d4, d7, d10, d13, d16, d19, d22, d25];
var d27 : UTF8.ValidUTF8Bytes := [];
var d28 : seq<StandardLibrary.UInt.uint8> := [];
var d29 : seq<StandardLibrary.UInt.uint8> := [];
var d30 : SerializableTypes.ESDKEncryptedDataKey := Aws.Crypto.EncryptedDataKey.EncryptedDataKey(keyProviderId:=d27,keyProviderInfo:=d28,ciphertext:=d29);
var d31 : SerializableTypes.ESDKEncryptedDataKeys := [d30];
var d32 : HeaderTypes.ContentType := HeaderTypes.ContentType.Framed;
var d33 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V1HeaderBody(messageType:=d0,esdkSuiteId:=64678,messageId:=d1,encryptionContext:=d26,encryptedDataKeys:=d31,contentType:=d32,headerIvLength:=2493,frameLength:=8);
var d34 : seq<StandardLibrary.UInt.uint8> := [];
var d35 : SerializableTypes.ESDKEncryptionContext := map[];
var d36 : Aws.Crypto.AlgorithmSuiteId := Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d37 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=32,tagLength:=16,ivLength:=12);
var d38 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d39 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.None;
var d40 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d41 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=50,id:=d36,encrypt:=d37,kdf:=d38,commitment:=d39,signature:=d40);
var d42 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d43 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d44 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d42,headerAuthTag:=d43);
var d45 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d33,rawHeader:=d34,encryptionContext:=d35,suite:=d41,headerAuth:=d44);
var d46 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d47 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0];
var d48 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d49 : Frames.Frame := Frames.Frame.RegularFrame(header:=d45,seqNum:=474,iv:=d46,encContent:=d47,authTag:=d48);
var r0 := MessageBody.BodyAADByFrameType(d49);
}
method {:test} test5() {
var d0 : HeaderTypes.MessageType := HeaderTypes.MessageType.TYPE_CUSTOMER_AED;
var d1 : HeaderTypes.MessageId := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d2 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d3 : UTF8.ValidUTF8Bytes := [];
var d4 : seq<StandardLibrary.UInt.uint8> := [];
var d5 : seq<StandardLibrary.UInt.uint8> := [];
var d6 : SerializableTypes.ESDKEncryptedDataKey := Aws.Crypto.EncryptedDataKey.EncryptedDataKey(keyProviderId:=d3,keyProviderInfo:=d4,ciphertext:=d5);
var d7 : SerializableTypes.ESDKEncryptedDataKeys := [d6];
var d8 : HeaderTypes.ContentType := HeaderTypes.ContentType.Framed;
var d9 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V1HeaderBody(messageType:=d0,esdkSuiteId:=2328,messageId:=d1,encryptionContext:=d2,encryptedDataKeys:=d7,contentType:=d8,headerIvLength:=4096,frameLength:=1);
var d10 : seq<StandardLibrary.UInt.uint8> := [];
var d11 : SerializableTypes.ESDKEncryptionContext := map[];
var d12 : Aws.Crypto.AlgorithmSuiteId := Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d13 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=16,tagLength:=16,ivLength:=12);
var d14 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d15 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.None;
var d16 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d17 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=129,id:=d12,encrypt:=d13,kdf:=d14,commitment:=d15,signature:=d16);
var d18 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d19 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d20 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d18,headerAuthTag:=d19);
var d21 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d9,rawHeader:=d10,encryptionContext:=d11,suite:=d17,headerAuth:=d20);
var d22 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d23 : seq<StandardLibrary.UInt.uint8> := [0];
var d24 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d25 : Frames.Frame := Frames.Frame.RegularFrame(header:=d21,seqNum:=7854,iv:=d22,encContent:=d23,authTag:=d24);
var d26 : HeaderTypes.MessageId := [];
var d27 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d28 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d29 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d30 : seq<StandardLibrary.UInt.uint8> := [];
var d31 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d26,encryptionContext:=d27,encryptedDataKeys:=d28,contentType:=d29,frameLength:=0,suiteData:=d30);
var d32 : seq<StandardLibrary.UInt.uint8> := [];
var d33 : SerializableTypes.ESDKEncryptionContext := map[];
var d34 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d35 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d36 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d37 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d38 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d39 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d34,encrypt:=d35,kdf:=d36,commitment:=d37,signature:=d38);
var d40 : seq<StandardLibrary.UInt.uint8> := [];
var d41 : seq<StandardLibrary.UInt.uint8> := [];
var d42 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d40,headerAuthTag:=d41);
var d43 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d31,rawHeader:=d32,encryptionContext:=d33,suite:=d39,headerAuth:=d42);
var d44 : seq<StandardLibrary.UInt.uint8> := [];
var d45 : seq<StandardLibrary.UInt.uint8> := [];
var d46 : seq<StandardLibrary.UInt.uint8> := [];
var d47 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d43,iv:=d44,encContent:=d45,authTag:=d46);
var d48 : HeaderTypes.MessageId := [];
var d49 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d50 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d51 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d52 : seq<StandardLibrary.UInt.uint8> := [];
var d53 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d48,encryptionContext:=d49,encryptedDataKeys:=d50,contentType:=d51,frameLength:=0,suiteData:=d52);
var d54 : seq<StandardLibrary.UInt.uint8> := [];
var d55 : SerializableTypes.ESDKEncryptionContext := map[];
var d56 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d57 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d58 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d59 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d60 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d61 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d56,encrypt:=d57,kdf:=d58,commitment:=d59,signature:=d60);
var d62 : seq<StandardLibrary.UInt.uint8> := [];
var d63 : seq<StandardLibrary.UInt.uint8> := [];
var d64 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d62,headerAuthTag:=d63);
var d65 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d53,rawHeader:=d54,encryptionContext:=d55,suite:=d61,headerAuth:=d64);
var d66 : seq<StandardLibrary.UInt.uint8> := [];
var d67 : seq<StandardLibrary.UInt.uint8> := [];
var d68 : seq<StandardLibrary.UInt.uint8> := [];
var d69 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d65,iv:=d66,encContent:=d67,authTag:=d68);
var d70 : HeaderTypes.MessageId := [];
var d71 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d72 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d73 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d74 : seq<StandardLibrary.UInt.uint8> := [];
var d75 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d70,encryptionContext:=d71,encryptedDataKeys:=d72,contentType:=d73,frameLength:=0,suiteData:=d74);
var d76 : seq<StandardLibrary.UInt.uint8> := [];
var d77 : SerializableTypes.ESDKEncryptionContext := map[];
var d78 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d79 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d80 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d81 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d82 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d83 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d78,encrypt:=d79,kdf:=d80,commitment:=d81,signature:=d82);
var d84 : seq<StandardLibrary.UInt.uint8> := [];
var d85 : seq<StandardLibrary.UInt.uint8> := [];
var d86 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d84,headerAuthTag:=d85);
var d87 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d75,rawHeader:=d76,encryptionContext:=d77,suite:=d83,headerAuth:=d86);
var d88 : seq<StandardLibrary.UInt.uint8> := [];
var d89 : seq<StandardLibrary.UInt.uint8> := [];
var d90 : seq<StandardLibrary.UInt.uint8> := [];
var d91 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d87,iv:=d88,encContent:=d89,authTag:=d90);
var d92 : HeaderTypes.MessageId := [];
var d93 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d94 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d95 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d96 : seq<StandardLibrary.UInt.uint8> := [];
var d97 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d92,encryptionContext:=d93,encryptedDataKeys:=d94,contentType:=d95,frameLength:=0,suiteData:=d96);
var d98 : seq<StandardLibrary.UInt.uint8> := [];
var d99 : SerializableTypes.ESDKEncryptionContext := map[];
var d100 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d101 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d102 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d103 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d104 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d105 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d100,encrypt:=d101,kdf:=d102,commitment:=d103,signature:=d104);
var d106 : seq<StandardLibrary.UInt.uint8> := [];
var d107 : seq<StandardLibrary.UInt.uint8> := [];
var d108 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d106,headerAuthTag:=d107);
var d109 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d97,rawHeader:=d98,encryptionContext:=d99,suite:=d105,headerAuth:=d108);
var d110 : seq<StandardLibrary.UInt.uint8> := [];
var d111 : seq<StandardLibrary.UInt.uint8> := [];
var d112 : seq<StandardLibrary.UInt.uint8> := [];
var d113 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d109,iv:=d110,encContent:=d111,authTag:=d112);
var d114 : HeaderTypes.MessageId := [];
var d115 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d116 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d117 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d118 : seq<StandardLibrary.UInt.uint8> := [];
var d119 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d114,encryptionContext:=d115,encryptedDataKeys:=d116,contentType:=d117,frameLength:=0,suiteData:=d118);
var d120 : seq<StandardLibrary.UInt.uint8> := [];
var d121 : SerializableTypes.ESDKEncryptionContext := map[];
var d122 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d123 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d124 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d125 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d126 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d127 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d122,encrypt:=d123,kdf:=d124,commitment:=d125,signature:=d126);
var d128 : seq<StandardLibrary.UInt.uint8> := [];
var d129 : seq<StandardLibrary.UInt.uint8> := [];
var d130 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d128,headerAuthTag:=d129);
var d131 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d119,rawHeader:=d120,encryptionContext:=d121,suite:=d127,headerAuth:=d130);
var d132 : seq<StandardLibrary.UInt.uint8> := [];
var d133 : seq<StandardLibrary.UInt.uint8> := [];
var d134 : seq<StandardLibrary.UInt.uint8> := [];
var d135 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d131,iv:=d132,encContent:=d133,authTag:=d134);
var d136 : HeaderTypes.MessageId := [];
var d137 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d138 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d139 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d140 : seq<StandardLibrary.UInt.uint8> := [];
var d141 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d136,encryptionContext:=d137,encryptedDataKeys:=d138,contentType:=d139,frameLength:=0,suiteData:=d140);
var d142 : seq<StandardLibrary.UInt.uint8> := [];
var d143 : SerializableTypes.ESDKEncryptionContext := map[];
var d144 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d145 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d146 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d147 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d148 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d149 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d144,encrypt:=d145,kdf:=d146,commitment:=d147,signature:=d148);
var d150 : seq<StandardLibrary.UInt.uint8> := [];
var d151 : seq<StandardLibrary.UInt.uint8> := [];
var d152 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d150,headerAuthTag:=d151);
var d153 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d141,rawHeader:=d142,encryptionContext:=d143,suite:=d149,headerAuth:=d152);
var d154 : seq<StandardLibrary.UInt.uint8> := [];
var d155 : seq<StandardLibrary.UInt.uint8> := [];
var d156 : seq<StandardLibrary.UInt.uint8> := [];
var d157 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d153,iv:=d154,encContent:=d155,authTag:=d156);
var d158 : HeaderTypes.MessageId := [];
var d159 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d160 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d161 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d162 : seq<StandardLibrary.UInt.uint8> := [];
var d163 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d158,encryptionContext:=d159,encryptedDataKeys:=d160,contentType:=d161,frameLength:=0,suiteData:=d162);
var d164 : seq<StandardLibrary.UInt.uint8> := [];
var d165 : SerializableTypes.ESDKEncryptionContext := map[];
var d166 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d167 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d168 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d169 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d170 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d171 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d166,encrypt:=d167,kdf:=d168,commitment:=d169,signature:=d170);
var d172 : seq<StandardLibrary.UInt.uint8> := [];
var d173 : seq<StandardLibrary.UInt.uint8> := [];
var d174 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d172,headerAuthTag:=d173);
var d175 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d163,rawHeader:=d164,encryptionContext:=d165,suite:=d171,headerAuth:=d174);
var d176 : seq<StandardLibrary.UInt.uint8> := [];
var d177 : seq<StandardLibrary.UInt.uint8> := [];
var d178 : seq<StandardLibrary.UInt.uint8> := [];
var d179 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d175,iv:=d176,encContent:=d177,authTag:=d178);
var d180 : HeaderTypes.MessageId := [];
var d181 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d182 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d183 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d184 : seq<StandardLibrary.UInt.uint8> := [];
var d185 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d180,encryptionContext:=d181,encryptedDataKeys:=d182,contentType:=d183,frameLength:=0,suiteData:=d184);
var d186 : seq<StandardLibrary.UInt.uint8> := [];
var d187 : SerializableTypes.ESDKEncryptionContext := map[];
var d188 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d189 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d190 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d191 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d192 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d193 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d188,encrypt:=d189,kdf:=d190,commitment:=d191,signature:=d192);
var d194 : seq<StandardLibrary.UInt.uint8> := [];
var d195 : seq<StandardLibrary.UInt.uint8> := [];
var d196 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d194,headerAuthTag:=d195);
var d197 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d185,rawHeader:=d186,encryptionContext:=d187,suite:=d193,headerAuth:=d196);
var d198 : seq<StandardLibrary.UInt.uint8> := [];
var d199 : seq<StandardLibrary.UInt.uint8> := [];
var d200 : seq<StandardLibrary.UInt.uint8> := [];
var d201 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d197,iv:=d198,encContent:=d199,authTag:=d200);
var d202 : HeaderTypes.MessageId := [];
var d203 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d204 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d205 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d206 : seq<StandardLibrary.UInt.uint8> := [];
var d207 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d202,encryptionContext:=d203,encryptedDataKeys:=d204,contentType:=d205,frameLength:=0,suiteData:=d206);
var d208 : seq<StandardLibrary.UInt.uint8> := [];
var d209 : SerializableTypes.ESDKEncryptionContext := map[];
var d210 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d211 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d212 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d213 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d214 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d215 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d210,encrypt:=d211,kdf:=d212,commitment:=d213,signature:=d214);
var d216 : seq<StandardLibrary.UInt.uint8> := [];
var d217 : seq<StandardLibrary.UInt.uint8> := [];
var d218 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d216,headerAuthTag:=d217);
var d219 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d207,rawHeader:=d208,encryptionContext:=d209,suite:=d215,headerAuth:=d218);
var d220 : seq<StandardLibrary.UInt.uint8> := [];
var d221 : seq<StandardLibrary.UInt.uint8> := [];
var d222 : seq<StandardLibrary.UInt.uint8> := [];
var d223 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d219,iv:=d220,encContent:=d221,authTag:=d222);
var d224 : HeaderTypes.MessageId := [];
var d225 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d226 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d227 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d228 : seq<StandardLibrary.UInt.uint8> := [];
var d229 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d224,encryptionContext:=d225,encryptedDataKeys:=d226,contentType:=d227,frameLength:=0,suiteData:=d228);
var d230 : seq<StandardLibrary.UInt.uint8> := [];
var d231 : SerializableTypes.ESDKEncryptionContext := map[];
var d232 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d233 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d234 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d235 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d236 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d237 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d232,encrypt:=d233,kdf:=d234,commitment:=d235,signature:=d236);
var d238 : seq<StandardLibrary.UInt.uint8> := [];
var d239 : seq<StandardLibrary.UInt.uint8> := [];
var d240 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d238,headerAuthTag:=d239);
var d241 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d229,rawHeader:=d230,encryptionContext:=d231,suite:=d237,headerAuth:=d240);
var d242 : seq<StandardLibrary.UInt.uint8> := [];
var d243 : seq<StandardLibrary.UInt.uint8> := [];
var d244 : seq<StandardLibrary.UInt.uint8> := [];
var d245 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d241,iv:=d242,encContent:=d243,authTag:=d244);
var d246 : HeaderTypes.MessageId := [];
var d247 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d248 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d249 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d250 : seq<StandardLibrary.UInt.uint8> := [];
var d251 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d246,encryptionContext:=d247,encryptedDataKeys:=d248,contentType:=d249,frameLength:=0,suiteData:=d250);
var d252 : seq<StandardLibrary.UInt.uint8> := [];
var d253 : SerializableTypes.ESDKEncryptionContext := map[];
var d254 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d255 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d256 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d257 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d258 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d259 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d254,encrypt:=d255,kdf:=d256,commitment:=d257,signature:=d258);
var d260 : seq<StandardLibrary.UInt.uint8> := [];
var d261 : seq<StandardLibrary.UInt.uint8> := [];
var d262 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d260,headerAuthTag:=d261);
var d263 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d251,rawHeader:=d252,encryptionContext:=d253,suite:=d259,headerAuth:=d262);
var d264 : seq<StandardLibrary.UInt.uint8> := [];
var d265 : seq<StandardLibrary.UInt.uint8> := [];
var d266 : seq<StandardLibrary.UInt.uint8> := [];
var d267 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d263,iv:=d264,encContent:=d265,authTag:=d266);
var d268 : HeaderTypes.MessageId := [];
var d269 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d270 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d271 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d272 : seq<StandardLibrary.UInt.uint8> := [];
var d273 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d268,encryptionContext:=d269,encryptedDataKeys:=d270,contentType:=d271,frameLength:=0,suiteData:=d272);
var d274 : seq<StandardLibrary.UInt.uint8> := [];
var d275 : SerializableTypes.ESDKEncryptionContext := map[];
var d276 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d277 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d278 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d279 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d280 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d281 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d276,encrypt:=d277,kdf:=d278,commitment:=d279,signature:=d280);
var d282 : seq<StandardLibrary.UInt.uint8> := [];
var d283 : seq<StandardLibrary.UInt.uint8> := [];
var d284 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d282,headerAuthTag:=d283);
var d285 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d273,rawHeader:=d274,encryptionContext:=d275,suite:=d281,headerAuth:=d284);
var d286 : seq<StandardLibrary.UInt.uint8> := [];
var d287 : seq<StandardLibrary.UInt.uint8> := [];
var d288 : seq<StandardLibrary.UInt.uint8> := [];
var d289 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d285,iv:=d286,encContent:=d287,authTag:=d288);
var d290 : HeaderTypes.MessageId := [];
var d291 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d292 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d293 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d294 : seq<StandardLibrary.UInt.uint8> := [];
var d295 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d290,encryptionContext:=d291,encryptedDataKeys:=d292,contentType:=d293,frameLength:=0,suiteData:=d294);
var d296 : seq<StandardLibrary.UInt.uint8> := [];
var d297 : SerializableTypes.ESDKEncryptionContext := map[];
var d298 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d299 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d300 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d301 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d302 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d303 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d298,encrypt:=d299,kdf:=d300,commitment:=d301,signature:=d302);
var d304 : seq<StandardLibrary.UInt.uint8> := [];
var d305 : seq<StandardLibrary.UInt.uint8> := [];
var d306 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d304,headerAuthTag:=d305);
var d307 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d295,rawHeader:=d296,encryptionContext:=d297,suite:=d303,headerAuth:=d306);
var d308 : seq<StandardLibrary.UInt.uint8> := [];
var d309 : seq<StandardLibrary.UInt.uint8> := [];
var d310 : seq<StandardLibrary.UInt.uint8> := [];
var d311 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d307,iv:=d308,encContent:=d309,authTag:=d310);
var d312 : HeaderTypes.MessageId := [];
var d313 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d314 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d315 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d316 : seq<StandardLibrary.UInt.uint8> := [];
var d317 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d312,encryptionContext:=d313,encryptedDataKeys:=d314,contentType:=d315,frameLength:=0,suiteData:=d316);
var d318 : seq<StandardLibrary.UInt.uint8> := [];
var d319 : SerializableTypes.ESDKEncryptionContext := map[];
var d320 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d321 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d322 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d323 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d324 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d325 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d320,encrypt:=d321,kdf:=d322,commitment:=d323,signature:=d324);
var d326 : seq<StandardLibrary.UInt.uint8> := [];
var d327 : seq<StandardLibrary.UInt.uint8> := [];
var d328 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d326,headerAuthTag:=d327);
var d329 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d317,rawHeader:=d318,encryptionContext:=d319,suite:=d325,headerAuth:=d328);
var d330 : seq<StandardLibrary.UInt.uint8> := [];
var d331 : seq<StandardLibrary.UInt.uint8> := [];
var d332 : seq<StandardLibrary.UInt.uint8> := [];
var d333 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d329,iv:=d330,encContent:=d331,authTag:=d332);
var d334 : HeaderTypes.MessageType := HeaderTypes.MessageType.TYPE_CUSTOMER_AED;
var d335 : HeaderTypes.MessageId := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d336 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d337 : UTF8.ValidUTF8Bytes := [];
var d338 : seq<StandardLibrary.UInt.uint8> := [];
var d339 : seq<StandardLibrary.UInt.uint8> := [];
var d340 : SerializableTypes.ESDKEncryptedDataKey := Aws.Crypto.EncryptedDataKey.EncryptedDataKey(keyProviderId:=d337,keyProviderInfo:=d338,ciphertext:=d339);
var d341 : SerializableTypes.ESDKEncryptedDataKeys := [d340];
var d342 : HeaderTypes.ContentType := HeaderTypes.ContentType.Framed;
var d343 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V1HeaderBody(messageType:=d334,esdkSuiteId:=2328,messageId:=d335,encryptionContext:=d336,encryptedDataKeys:=d341,contentType:=d342,headerIvLength:=4096,frameLength:=1);
var d344 : seq<StandardLibrary.UInt.uint8> := [];
var d345 : SerializableTypes.ESDKEncryptionContext := map[];
var d346 : Aws.Crypto.AlgorithmSuiteId := Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d347 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=16,tagLength:=16,ivLength:=12);
var d348 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d349 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.None;
var d350 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d351 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=129,id:=d346,encrypt:=d347,kdf:=d348,commitment:=d349,signature:=d350);
var d352 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d353 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d354 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d352,headerAuthTag:=d353);
var d355 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d343,rawHeader:=d344,encryptionContext:=d345,suite:=d351,headerAuth:=d354);
var d356 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d357 : seq<StandardLibrary.UInt.uint8> := [0];
var d358 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d359 : Frames.Frame := Frames.Frame.RegularFrame(header:=d355,seqNum:=5941,iv:=d356,encContent:=d357,authTag:=d358);
var d360 : HeaderTypes.MessageType := HeaderTypes.MessageType.TYPE_CUSTOMER_AED;
var d361 : HeaderTypes.MessageId := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d362 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d363 : UTF8.ValidUTF8Bytes := [];
var d364 : seq<StandardLibrary.UInt.uint8> := [];
var d365 : seq<StandardLibrary.UInt.uint8> := [];
var d366 : SerializableTypes.ESDKEncryptedDataKey := Aws.Crypto.EncryptedDataKey.EncryptedDataKey(keyProviderId:=d363,keyProviderInfo:=d364,ciphertext:=d365);
var d367 : SerializableTypes.ESDKEncryptedDataKeys := [d366];
var d368 : HeaderTypes.ContentType := HeaderTypes.ContentType.Framed;
var d369 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V1HeaderBody(messageType:=d360,esdkSuiteId:=2328,messageId:=d361,encryptionContext:=d362,encryptedDataKeys:=d367,contentType:=d368,headerIvLength:=4096,frameLength:=1);
var d370 : seq<StandardLibrary.UInt.uint8> := [];
var d371 : SerializableTypes.ESDKEncryptionContext := map[];
var d372 : Aws.Crypto.AlgorithmSuiteId := Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d373 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=16,tagLength:=16,ivLength:=12);
var d374 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d375 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.None;
var d376 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d377 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=129,id:=d372,encrypt:=d373,kdf:=d374,commitment:=d375,signature:=d376);
var d378 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d379 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d380 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d378,headerAuthTag:=d379);
var d381 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d369,rawHeader:=d370,encryptionContext:=d371,suite:=d377,headerAuth:=d380);
var d382 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d383 : seq<StandardLibrary.UInt.uint8> := [0];
var d384 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d385 : Frames.Frame := Frames.Frame.RegularFrame(header:=d381,seqNum:=17,iv:=d382,encContent:=d383,authTag:=d384);
var d386 : MessageBody.MessageRegularFrames := [d25, d47, d69, d91, d113, d135, d157, d179, d201, d223, d245, d267, d289, d311, d333, d359, d385];
var d387 : HeaderTypes.MessageType := HeaderTypes.MessageType.TYPE_CUSTOMER_AED;
var d388 : HeaderTypes.MessageId := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d389 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d390 : UTF8.ValidUTF8Bytes := [];
var d391 : seq<StandardLibrary.UInt.uint8> := [];
var d392 : seq<StandardLibrary.UInt.uint8> := [];
var d393 : SerializableTypes.ESDKEncryptedDataKey := Aws.Crypto.EncryptedDataKey.EncryptedDataKey(keyProviderId:=d390,keyProviderInfo:=d391,ciphertext:=d392);
var d394 : SerializableTypes.ESDKEncryptedDataKeys := [d393];
var d395 : HeaderTypes.ContentType := HeaderTypes.ContentType.Framed;
var d396 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V1HeaderBody(messageType:=d387,esdkSuiteId:=2328,messageId:=d388,encryptionContext:=d389,encryptedDataKeys:=d394,contentType:=d395,headerIvLength:=4096,frameLength:=1);
var d397 : seq<StandardLibrary.UInt.uint8> := [];
var d398 : SerializableTypes.ESDKEncryptionContext := map[];
var d399 : Aws.Crypto.AlgorithmSuiteId := Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d400 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=16,tagLength:=16,ivLength:=12);
var d401 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d402 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.None;
var d403 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d404 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=129,id:=d399,encrypt:=d400,kdf:=d401,commitment:=d402,signature:=d403);
var d405 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d406 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d407 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d405,headerAuthTag:=d406);
var d408 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d396,rawHeader:=d397,encryptionContext:=d398,suite:=d404,headerAuth:=d407);
var d409 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d410 : seq<StandardLibrary.UInt.uint8> := [0];
var d411 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d412 : Frames.FinalFrame := Frames.Frame.FinalFrame(header:=d408,seqNum:=18,iv:=d409,encContent:=d410,authTag:=d411);
var d413 : MessageBody.FramedMessageBody := MessageBody.FramedMessageBody.FramedMessageBody(regularFrames:=d386,finalFrame:=d412);
var d414 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var r0 := MessageBody.DecryptFramedMessageBody(d413, d414);
}
method {:test} test6() {
var d0 : HeaderTypes.MessageType := HeaderTypes.MessageType.TYPE_CUSTOMER_AED;
var d1 : HeaderTypes.MessageId := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d2 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d3 : UTF8.ValidUTF8Bytes := [];
var d4 : seq<StandardLibrary.UInt.uint8> := [];
var d5 : seq<StandardLibrary.UInt.uint8> := [];
var d6 : SerializableTypes.ESDKEncryptedDataKey := Aws.Crypto.EncryptedDataKey.EncryptedDataKey(keyProviderId:=d3,keyProviderInfo:=d4,ciphertext:=d5);
var d7 : SerializableTypes.ESDKEncryptedDataKeys := [d6];
var d8 : HeaderTypes.ContentType := HeaderTypes.ContentType.Framed;
var d9 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V1HeaderBody(messageType:=d0,esdkSuiteId:=1381,messageId:=d1,encryptionContext:=d2,encryptedDataKeys:=d7,contentType:=d8,headerIvLength:=3212,frameLength:=18);
var d10 : seq<StandardLibrary.UInt.uint8> := [];
var d11 : SerializableTypes.ESDKEncryptionContext := map[];
var d12 : Aws.Crypto.AlgorithmSuiteId := Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d13 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=16,tagLength:=16,ivLength:=12);
var d14 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d15 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.None;
var d16 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d17 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=84,id:=d12,encrypt:=d13,kdf:=d14,commitment:=d15,signature:=d16);
var d18 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d19 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d20 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d18,headerAuthTag:=d19);
var d21 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d9,rawHeader:=d10,encryptionContext:=d11,suite:=d17,headerAuth:=d20);
var d22 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d23 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d24 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d25 : Frames.Frame := Frames.Frame.RegularFrame(header:=d21,seqNum:=3504,iv:=d22,encContent:=d23,authTag:=d24);
var d26 : HeaderTypes.MessageId := [];
var d27 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d28 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d29 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d30 : seq<StandardLibrary.UInt.uint8> := [];
var d31 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d26,encryptionContext:=d27,encryptedDataKeys:=d28,contentType:=d29,frameLength:=0,suiteData:=d30);
var d32 : seq<StandardLibrary.UInt.uint8> := [];
var d33 : SerializableTypes.ESDKEncryptionContext := map[];
var d34 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d35 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d36 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d37 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d38 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d39 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d34,encrypt:=d35,kdf:=d36,commitment:=d37,signature:=d38);
var d40 : seq<StandardLibrary.UInt.uint8> := [];
var d41 : seq<StandardLibrary.UInt.uint8> := [];
var d42 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d40,headerAuthTag:=d41);
var d43 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d31,rawHeader:=d32,encryptionContext:=d33,suite:=d39,headerAuth:=d42);
var d44 : seq<StandardLibrary.UInt.uint8> := [];
var d45 : seq<StandardLibrary.UInt.uint8> := [];
var d46 : seq<StandardLibrary.UInt.uint8> := [];
var d47 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d43,iv:=d44,encContent:=d45,authTag:=d46);
var d48 : HeaderTypes.MessageId := [];
var d49 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d50 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d51 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d52 : seq<StandardLibrary.UInt.uint8> := [];
var d53 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d48,encryptionContext:=d49,encryptedDataKeys:=d50,contentType:=d51,frameLength:=0,suiteData:=d52);
var d54 : seq<StandardLibrary.UInt.uint8> := [];
var d55 : SerializableTypes.ESDKEncryptionContext := map[];
var d56 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d57 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d58 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d59 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d60 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d61 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d56,encrypt:=d57,kdf:=d58,commitment:=d59,signature:=d60);
var d62 : seq<StandardLibrary.UInt.uint8> := [];
var d63 : seq<StandardLibrary.UInt.uint8> := [];
var d64 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d62,headerAuthTag:=d63);
var d65 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d53,rawHeader:=d54,encryptionContext:=d55,suite:=d61,headerAuth:=d64);
var d66 : seq<StandardLibrary.UInt.uint8> := [];
var d67 : seq<StandardLibrary.UInt.uint8> := [];
var d68 : seq<StandardLibrary.UInt.uint8> := [];
var d69 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d65,iv:=d66,encContent:=d67,authTag:=d68);
var d70 : HeaderTypes.MessageId := [];
var d71 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d72 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d73 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d74 : seq<StandardLibrary.UInt.uint8> := [];
var d75 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d70,encryptionContext:=d71,encryptedDataKeys:=d72,contentType:=d73,frameLength:=0,suiteData:=d74);
var d76 : seq<StandardLibrary.UInt.uint8> := [];
var d77 : SerializableTypes.ESDKEncryptionContext := map[];
var d78 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d79 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d80 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d81 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d82 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d83 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d78,encrypt:=d79,kdf:=d80,commitment:=d81,signature:=d82);
var d84 : seq<StandardLibrary.UInt.uint8> := [];
var d85 : seq<StandardLibrary.UInt.uint8> := [];
var d86 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d84,headerAuthTag:=d85);
var d87 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d75,rawHeader:=d76,encryptionContext:=d77,suite:=d83,headerAuth:=d86);
var d88 : seq<StandardLibrary.UInt.uint8> := [];
var d89 : seq<StandardLibrary.UInt.uint8> := [];
var d90 : seq<StandardLibrary.UInt.uint8> := [];
var d91 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d87,iv:=d88,encContent:=d89,authTag:=d90);
var d92 : HeaderTypes.MessageId := [];
var d93 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d94 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d95 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d96 : seq<StandardLibrary.UInt.uint8> := [];
var d97 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d92,encryptionContext:=d93,encryptedDataKeys:=d94,contentType:=d95,frameLength:=0,suiteData:=d96);
var d98 : seq<StandardLibrary.UInt.uint8> := [];
var d99 : SerializableTypes.ESDKEncryptionContext := map[];
var d100 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d101 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d102 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d103 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d104 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d105 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d100,encrypt:=d101,kdf:=d102,commitment:=d103,signature:=d104);
var d106 : seq<StandardLibrary.UInt.uint8> := [];
var d107 : seq<StandardLibrary.UInt.uint8> := [];
var d108 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d106,headerAuthTag:=d107);
var d109 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d97,rawHeader:=d98,encryptionContext:=d99,suite:=d105,headerAuth:=d108);
var d110 : seq<StandardLibrary.UInt.uint8> := [];
var d111 : seq<StandardLibrary.UInt.uint8> := [];
var d112 : seq<StandardLibrary.UInt.uint8> := [];
var d113 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d109,iv:=d110,encContent:=d111,authTag:=d112);
var d114 : HeaderTypes.MessageId := [];
var d115 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d116 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d117 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d118 : seq<StandardLibrary.UInt.uint8> := [];
var d119 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d114,encryptionContext:=d115,encryptedDataKeys:=d116,contentType:=d117,frameLength:=0,suiteData:=d118);
var d120 : seq<StandardLibrary.UInt.uint8> := [];
var d121 : SerializableTypes.ESDKEncryptionContext := map[];
var d122 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d123 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d124 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d125 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d126 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d127 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d122,encrypt:=d123,kdf:=d124,commitment:=d125,signature:=d126);
var d128 : seq<StandardLibrary.UInt.uint8> := [];
var d129 : seq<StandardLibrary.UInt.uint8> := [];
var d130 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d128,headerAuthTag:=d129);
var d131 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d119,rawHeader:=d120,encryptionContext:=d121,suite:=d127,headerAuth:=d130);
var d132 : seq<StandardLibrary.UInt.uint8> := [];
var d133 : seq<StandardLibrary.UInt.uint8> := [];
var d134 : seq<StandardLibrary.UInt.uint8> := [];
var d135 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d131,iv:=d132,encContent:=d133,authTag:=d134);
var d136 : HeaderTypes.MessageId := [];
var d137 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d138 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d139 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d140 : seq<StandardLibrary.UInt.uint8> := [];
var d141 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d136,encryptionContext:=d137,encryptedDataKeys:=d138,contentType:=d139,frameLength:=0,suiteData:=d140);
var d142 : seq<StandardLibrary.UInt.uint8> := [];
var d143 : SerializableTypes.ESDKEncryptionContext := map[];
var d144 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d145 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d146 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d147 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d148 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d149 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d144,encrypt:=d145,kdf:=d146,commitment:=d147,signature:=d148);
var d150 : seq<StandardLibrary.UInt.uint8> := [];
var d151 : seq<StandardLibrary.UInt.uint8> := [];
var d152 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d150,headerAuthTag:=d151);
var d153 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d141,rawHeader:=d142,encryptionContext:=d143,suite:=d149,headerAuth:=d152);
var d154 : seq<StandardLibrary.UInt.uint8> := [];
var d155 : seq<StandardLibrary.UInt.uint8> := [];
var d156 : seq<StandardLibrary.UInt.uint8> := [];
var d157 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d153,iv:=d154,encContent:=d155,authTag:=d156);
var d158 : HeaderTypes.MessageId := [];
var d159 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d160 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d161 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d162 : seq<StandardLibrary.UInt.uint8> := [];
var d163 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d158,encryptionContext:=d159,encryptedDataKeys:=d160,contentType:=d161,frameLength:=0,suiteData:=d162);
var d164 : seq<StandardLibrary.UInt.uint8> := [];
var d165 : SerializableTypes.ESDKEncryptionContext := map[];
var d166 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d167 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d168 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d169 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d170 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d171 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d166,encrypt:=d167,kdf:=d168,commitment:=d169,signature:=d170);
var d172 : seq<StandardLibrary.UInt.uint8> := [];
var d173 : seq<StandardLibrary.UInt.uint8> := [];
var d174 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d172,headerAuthTag:=d173);
var d175 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d163,rawHeader:=d164,encryptionContext:=d165,suite:=d171,headerAuth:=d174);
var d176 : seq<StandardLibrary.UInt.uint8> := [];
var d177 : seq<StandardLibrary.UInt.uint8> := [];
var d178 : seq<StandardLibrary.UInt.uint8> := [];
var d179 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d175,iv:=d176,encContent:=d177,authTag:=d178);
var d180 : HeaderTypes.MessageId := [];
var d181 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d182 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d183 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d184 : seq<StandardLibrary.UInt.uint8> := [];
var d185 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d180,encryptionContext:=d181,encryptedDataKeys:=d182,contentType:=d183,frameLength:=0,suiteData:=d184);
var d186 : seq<StandardLibrary.UInt.uint8> := [];
var d187 : SerializableTypes.ESDKEncryptionContext := map[];
var d188 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d189 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d190 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d191 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d192 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d193 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d188,encrypt:=d189,kdf:=d190,commitment:=d191,signature:=d192);
var d194 : seq<StandardLibrary.UInt.uint8> := [];
var d195 : seq<StandardLibrary.UInt.uint8> := [];
var d196 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d194,headerAuthTag:=d195);
var d197 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d185,rawHeader:=d186,encryptionContext:=d187,suite:=d193,headerAuth:=d196);
var d198 : seq<StandardLibrary.UInt.uint8> := [];
var d199 : seq<StandardLibrary.UInt.uint8> := [];
var d200 : seq<StandardLibrary.UInt.uint8> := [];
var d201 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d197,iv:=d198,encContent:=d199,authTag:=d200);
var d202 : HeaderTypes.MessageId := [];
var d203 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d204 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d205 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d206 : seq<StandardLibrary.UInt.uint8> := [];
var d207 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d202,encryptionContext:=d203,encryptedDataKeys:=d204,contentType:=d205,frameLength:=0,suiteData:=d206);
var d208 : seq<StandardLibrary.UInt.uint8> := [];
var d209 : SerializableTypes.ESDKEncryptionContext := map[];
var d210 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d211 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d212 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d213 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d214 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d215 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d210,encrypt:=d211,kdf:=d212,commitment:=d213,signature:=d214);
var d216 : seq<StandardLibrary.UInt.uint8> := [];
var d217 : seq<StandardLibrary.UInt.uint8> := [];
var d218 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d216,headerAuthTag:=d217);
var d219 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d207,rawHeader:=d208,encryptionContext:=d209,suite:=d215,headerAuth:=d218);
var d220 : seq<StandardLibrary.UInt.uint8> := [];
var d221 : seq<StandardLibrary.UInt.uint8> := [];
var d222 : seq<StandardLibrary.UInt.uint8> := [];
var d223 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d219,iv:=d220,encContent:=d221,authTag:=d222);
var d224 : HeaderTypes.MessageId := [];
var d225 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d226 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d227 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d228 : seq<StandardLibrary.UInt.uint8> := [];
var d229 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d224,encryptionContext:=d225,encryptedDataKeys:=d226,contentType:=d227,frameLength:=0,suiteData:=d228);
var d230 : seq<StandardLibrary.UInt.uint8> := [];
var d231 : SerializableTypes.ESDKEncryptionContext := map[];
var d232 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d233 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d234 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d235 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d236 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d237 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d232,encrypt:=d233,kdf:=d234,commitment:=d235,signature:=d236);
var d238 : seq<StandardLibrary.UInt.uint8> := [];
var d239 : seq<StandardLibrary.UInt.uint8> := [];
var d240 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d238,headerAuthTag:=d239);
var d241 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d229,rawHeader:=d230,encryptionContext:=d231,suite:=d237,headerAuth:=d240);
var d242 : seq<StandardLibrary.UInt.uint8> := [];
var d243 : seq<StandardLibrary.UInt.uint8> := [];
var d244 : seq<StandardLibrary.UInt.uint8> := [];
var d245 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d241,iv:=d242,encContent:=d243,authTag:=d244);
var d246 : HeaderTypes.MessageId := [];
var d247 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d248 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d249 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d250 : seq<StandardLibrary.UInt.uint8> := [];
var d251 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d246,encryptionContext:=d247,encryptedDataKeys:=d248,contentType:=d249,frameLength:=0,suiteData:=d250);
var d252 : seq<StandardLibrary.UInt.uint8> := [];
var d253 : SerializableTypes.ESDKEncryptionContext := map[];
var d254 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d255 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d256 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d257 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d258 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d259 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d254,encrypt:=d255,kdf:=d256,commitment:=d257,signature:=d258);
var d260 : seq<StandardLibrary.UInt.uint8> := [];
var d261 : seq<StandardLibrary.UInt.uint8> := [];
var d262 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d260,headerAuthTag:=d261);
var d263 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d251,rawHeader:=d252,encryptionContext:=d253,suite:=d259,headerAuth:=d262);
var d264 : seq<StandardLibrary.UInt.uint8> := [];
var d265 : seq<StandardLibrary.UInt.uint8> := [];
var d266 : seq<StandardLibrary.UInt.uint8> := [];
var d267 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d263,iv:=d264,encContent:=d265,authTag:=d266);
var d268 : HeaderTypes.MessageId := [];
var d269 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d270 : SerializableTypes.ESDKEncryptedDataKeys := [];
var d271 : HeaderTypes.ContentType := HeaderTypes.ContentType.NonFramed;
var d272 : seq<StandardLibrary.UInt.uint8> := [];
var d273 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V2HeaderBody(esdkSuiteId:=0,messageId:=d268,encryptionContext:=d269,encryptedDataKeys:=d270,contentType:=d271,frameLength:=0,suiteData:=d272);
var d274 : seq<StandardLibrary.UInt.uint8> := [];
var d275 : SerializableTypes.ESDKEncryptionContext := map[];
var d276 : Aws.Crypto.AlgorithmSuiteId := Aws.Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d277 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=0,tagLength:=0,ivLength:=0);
var d278 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d279 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d280 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d281 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=0,id:=d276,encrypt:=d277,kdf:=d278,commitment:=d279,signature:=d280);
var d282 : seq<StandardLibrary.UInt.uint8> := [];
var d283 : seq<StandardLibrary.UInt.uint8> := [];
var d284 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d282,headerAuthTag:=d283);
var d285 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d273,rawHeader:=d274,encryptionContext:=d275,suite:=d281,headerAuth:=d284);
var d286 : seq<StandardLibrary.UInt.uint8> := [];
var d287 : seq<StandardLibrary.UInt.uint8> := [];
var d288 : seq<StandardLibrary.UInt.uint8> := [];
var d289 : Frames.RegularFrame := Frames.Frame.NonFramed(header:=d285,iv:=d286,encContent:=d287,authTag:=d288);
var d290 : HeaderTypes.MessageType := HeaderTypes.MessageType.TYPE_CUSTOMER_AED;
var d291 : HeaderTypes.MessageId := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d292 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d293 : UTF8.ValidUTF8Bytes := [];
var d294 : seq<StandardLibrary.UInt.uint8> := [];
var d295 : seq<StandardLibrary.UInt.uint8> := [];
var d296 : SerializableTypes.ESDKEncryptedDataKey := Aws.Crypto.EncryptedDataKey.EncryptedDataKey(keyProviderId:=d293,keyProviderInfo:=d294,ciphertext:=d295);
var d297 : SerializableTypes.ESDKEncryptedDataKeys := [d296];
var d298 : HeaderTypes.ContentType := HeaderTypes.ContentType.Framed;
var d299 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V1HeaderBody(messageType:=d290,esdkSuiteId:=1381,messageId:=d291,encryptionContext:=d292,encryptedDataKeys:=d297,contentType:=d298,headerIvLength:=3212,frameLength:=18);
var d300 : seq<StandardLibrary.UInt.uint8> := [];
var d301 : SerializableTypes.ESDKEncryptionContext := map[];
var d302 : Aws.Crypto.AlgorithmSuiteId := Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d303 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=16,tagLength:=16,ivLength:=12);
var d304 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d305 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.None;
var d306 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d307 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=84,id:=d302,encrypt:=d303,kdf:=d304,commitment:=d305,signature:=d306);
var d308 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d309 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d310 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d308,headerAuthTag:=d309);
var d311 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d299,rawHeader:=d300,encryptionContext:=d301,suite:=d307,headerAuth:=d310);
var d312 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d313 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d314 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d315 : Frames.Frame := Frames.Frame.RegularFrame(header:=d311,seqNum:=14,iv:=d312,encContent:=d313,authTag:=d314);
var d316 : MessageBody.MessageRegularFrames := [d25, d47, d69, d91, d113, d135, d157, d179, d201, d223, d245, d267, d289, d315];
var d317 : HeaderTypes.MessageType := HeaderTypes.MessageType.TYPE_CUSTOMER_AED;
var d318 : HeaderTypes.MessageId := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d319 : EncryptionContext.ESDKCanonicalEncryptionContext := [];
var d320 : UTF8.ValidUTF8Bytes := [];
var d321 : seq<StandardLibrary.UInt.uint8> := [];
var d322 : seq<StandardLibrary.UInt.uint8> := [];
var d323 : SerializableTypes.ESDKEncryptedDataKey := Aws.Crypto.EncryptedDataKey.EncryptedDataKey(keyProviderId:=d320,keyProviderInfo:=d321,ciphertext:=d322);
var d324 : SerializableTypes.ESDKEncryptedDataKeys := [d323];
var d325 : HeaderTypes.ContentType := HeaderTypes.ContentType.Framed;
var d326 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V1HeaderBody(messageType:=d317,esdkSuiteId:=1381,messageId:=d318,encryptionContext:=d319,encryptedDataKeys:=d324,contentType:=d325,headerIvLength:=3212,frameLength:=18);
var d327 : seq<StandardLibrary.UInt.uint8> := [];
var d328 : SerializableTypes.ESDKEncryptionContext := map[];
var d329 : Aws.Crypto.AlgorithmSuiteId := Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d330 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=16,tagLength:=16,ivLength:=12);
var d331 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d332 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.None;
var d333 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d334 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=84,id:=d329,encrypt:=d330,kdf:=d331,commitment:=d332,signature:=d333);
var d335 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d336 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d337 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d335,headerAuthTag:=d336);
var d338 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d326,rawHeader:=d327,encryptionContext:=d328,suite:=d334,headerAuth:=d337);
var d339 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d340 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d341 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d342 : Frames.FinalFrame := Frames.Frame.FinalFrame(header:=d338,seqNum:=15,iv:=d339,encContent:=d340,authTag:=d341);
var d343 : MessageBody.FramedMessageBody := MessageBody.FramedMessageBody.FramedMessageBody(regularFrames:=d316,finalFrame:=d342);
var d344 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var r0 := MessageBody.DecryptFramedMessageBody(d343, d344);
}
method {:test} test7() {
var d0 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d1 : HeaderTypes.MessageType := HeaderTypes.MessageType.TYPE_CUSTOMER_AED;
var d2 : HeaderTypes.MessageId := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d3 : UTF8.ValidUTF8Bytes := [];
var d4 : UTF8.ValidUTF8Bytes := [];
var d5 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d3,value:=d4);
var d6 : UTF8.ValidUTF8Bytes := [];
var d7 : UTF8.ValidUTF8Bytes := [];
var d8 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d6,value:=d7);
var d9 : UTF8.ValidUTF8Bytes := [];
var d10 : UTF8.ValidUTF8Bytes := [];
var d11 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d9,value:=d10);
var d12 : UTF8.ValidUTF8Bytes := [];
var d13 : UTF8.ValidUTF8Bytes := [];
var d14 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d12,value:=d13);
var d15 : UTF8.ValidUTF8Bytes := [];
var d16 : UTF8.ValidUTF8Bytes := [];
var d17 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d15,value:=d16);
var d18 : UTF8.ValidUTF8Bytes := [];
var d19 : UTF8.ValidUTF8Bytes := [];
var d20 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d18,value:=d19);
var d21 : UTF8.ValidUTF8Bytes := [];
var d22 : UTF8.ValidUTF8Bytes := [];
var d23 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d21,value:=d22);
var d24 : UTF8.ValidUTF8Bytes := [];
var d25 : UTF8.ValidUTF8Bytes := [];
var d26 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d24,value:=d25);
var d27 : UTF8.ValidUTF8Bytes := [];
var d28 : UTF8.ValidUTF8Bytes := [];
var d29 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d27,value:=d28);
var d30 : UTF8.ValidUTF8Bytes := [];
var d31 : UTF8.ValidUTF8Bytes := [];
var d32 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d30,value:=d31);
var d33 : UTF8.ValidUTF8Bytes := [];
var d34 : UTF8.ValidUTF8Bytes := [];
var d35 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d33,value:=d34);
var d36 : UTF8.ValidUTF8Bytes := [];
var d37 : UTF8.ValidUTF8Bytes := [];
var d38 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d36,value:=d37);
var d39 : UTF8.ValidUTF8Bytes := [];
var d40 : UTF8.ValidUTF8Bytes := [];
var d41 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d39,value:=d40);
var d42 : UTF8.ValidUTF8Bytes := [];
var d43 : UTF8.ValidUTF8Bytes := [];
var d44 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d42,value:=d43);
var d45 : UTF8.ValidUTF8Bytes := [205, 148, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d46 : UTF8.ValidUTF8Bytes := [211, 169, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d47 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d45,value:=d46);
var d48 : UTF8.ValidUTF8Bytes := [209, 172, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d49 : UTF8.ValidUTF8Bytes := [221, 173, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d50 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d48,value:=d49);
var d51 : UTF8.ValidUTF8Bytes := [214, 140, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d52 : UTF8.ValidUTF8Bytes := [197, 177, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d53 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d51,value:=d52);
var d54 : UTF8.ValidUTF8Bytes := [200, 175, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d55 : UTF8.ValidUTF8Bytes := [217, 142, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d56 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d54,value:=d55);
var d57 : EncryptionContext.ESDKCanonicalEncryptionContext := [d5, d8, d11, d14, d17, d20, d23, d26, d29, d32, d35, d38, d41, d44, d47, d50, d53, d56];
var d58 : UTF8.ValidUTF8Bytes := [];
var d59 : seq<StandardLibrary.UInt.uint8> := [];
var d60 : seq<StandardLibrary.UInt.uint8> := [];
var d61 : SerializableTypes.ESDKEncryptedDataKey := Aws.Crypto.EncryptedDataKey.EncryptedDataKey(keyProviderId:=d58,keyProviderInfo:=d59,ciphertext:=d60);
var d62 : SerializableTypes.ESDKEncryptedDataKeys := [d61];
var d63 : HeaderTypes.ContentType := HeaderTypes.ContentType.Framed;
var d64 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V1HeaderBody(messageType:=d1,esdkSuiteId:=4765,messageId:=d2,encryptionContext:=d57,encryptedDataKeys:=d62,contentType:=d63,headerIvLength:=6337,frameLength:=19);
var d65 : seq<StandardLibrary.UInt.uint8> := [];
var d66 : SerializableTypes.ESDKEncryptionContext := map[];
var d67 : Aws.Crypto.AlgorithmSuiteId := Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d68 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=16,tagLength:=16,ivLength:=12);
var d69 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d70 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.None;
var d71 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d72 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=63,id:=d67,encrypt:=d68,kdf:=d69,commitment:=d70,signature:=d71);
var d73 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d74 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d75 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d73,headerAuthTag:=d74);
var d76 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d64,rawHeader:=d65,encryptionContext:=d66,suite:=d72,headerAuth:=d75);
var d77 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var r0 := MessageBody.EncryptRegularFrame(d0, d76, d77, (3738144892 as StandardLibrary.UInt.uint32));
}
method {:test} test8() {
var d0 : seq<StandardLibrary.UInt.uint8> := [0];
var d1 : HeaderTypes.MessageType := HeaderTypes.MessageType.TYPE_CUSTOMER_AED;
var d2 : HeaderTypes.MessageId := [0, 0, 0, 0, 0, 0, 0, 0, 0];
var d3 : UTF8.ValidUTF8Bytes := [];
var d4 : UTF8.ValidUTF8Bytes := [];
var d5 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d3,value:=d4);
var d6 : UTF8.ValidUTF8Bytes := [];
var d7 : UTF8.ValidUTF8Bytes := [];
var d8 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d6,value:=d7);
var d9 : UTF8.ValidUTF8Bytes := [];
var d10 : UTF8.ValidUTF8Bytes := [];
var d11 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d9,value:=d10);
var d12 : UTF8.ValidUTF8Bytes := [];
var d13 : UTF8.ValidUTF8Bytes := [];
var d14 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d12,value:=d13);
var d15 : UTF8.ValidUTF8Bytes := [];
var d16 : UTF8.ValidUTF8Bytes := [];
var d17 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d15,value:=d16);
var d18 : UTF8.ValidUTF8Bytes := [];
var d19 : UTF8.ValidUTF8Bytes := [];
var d20 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d18,value:=d19);
var d21 : UTF8.ValidUTF8Bytes := [];
var d22 : UTF8.ValidUTF8Bytes := [];
var d23 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d21,value:=d22);
var d24 : UTF8.ValidUTF8Bytes := [];
var d25 : UTF8.ValidUTF8Bytes := [];
var d26 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d24,value:=d25);
var d27 : UTF8.ValidUTF8Bytes := [];
var d28 : UTF8.ValidUTF8Bytes := [];
var d29 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d27,value:=d28);
var d30 : UTF8.ValidUTF8Bytes := [];
var d31 : UTF8.ValidUTF8Bytes := [];
var d32 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d30,value:=d31);
var d33 : UTF8.ValidUTF8Bytes := [];
var d34 : UTF8.ValidUTF8Bytes := [];
var d35 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d33,value:=d34);
var d36 : UTF8.ValidUTF8Bytes := [];
var d37 : UTF8.ValidUTF8Bytes := [];
var d38 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d36,value:=d37);
var d39 : UTF8.ValidUTF8Bytes := [];
var d40 : UTF8.ValidUTF8Bytes := [];
var d41 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d39,value:=d40);
var d42 : UTF8.ValidUTF8Bytes := [];
var d43 : UTF8.ValidUTF8Bytes := [];
var d44 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d42,value:=d43);
var d45 : UTF8.ValidUTF8Bytes := [];
var d46 : UTF8.ValidUTF8Bytes := [];
var d47 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d45,value:=d46);
var d48 : UTF8.ValidUTF8Bytes := [];
var d49 : UTF8.ValidUTF8Bytes := [];
var d50 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d48,value:=d49);
var d51 : UTF8.ValidUTF8Bytes := [208, 174, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d52 : UTF8.ValidUTF8Bytes := [210, 147, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d53 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d51,value:=d52);
var d54 : UTF8.ValidUTF8Bytes := [221, 168, 0, 0, 0, 0, 0];
var d55 : UTF8.ValidUTF8Bytes := [221, 140];
var d56 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d54,value:=d55);
var d57 : UTF8.ValidUTF8Bytes := [202, 167, 0, 0, 0, 0, 0, 0, 0, 0];
var d58 : UTF8.ValidUTF8Bytes := [206, 144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d59 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d57,value:=d58);
var d60 : UTF8.ValidUTF8Bytes := [222, 147, 0, 0, 0, 0, 0, 0, 0];
var d61 : UTF8.ValidUTF8Bytes := [206, 152, 0, 0, 0, 0, 0, 0, 0];
var d62 : EncryptionContext.ESDKEncryptionContextPair := SerializableTypes.Pair<UTF8.ValidUTF8Bytes, UTF8.ValidUTF8Bytes>.Pair(key:=d60,value:=d61);
var d63 : EncryptionContext.ESDKCanonicalEncryptionContext := [d5, d8, d11, d14, d17, d20, d23, d26, d29, d32, d35, d38, d41, d44, d47, d50, d53, d56, d59, d62];
var d64 : UTF8.ValidUTF8Bytes := [];
var d65 : seq<StandardLibrary.UInt.uint8> := [];
var d66 : seq<StandardLibrary.UInt.uint8> := [];
var d67 : SerializableTypes.ESDKEncryptedDataKey := Aws.Crypto.EncryptedDataKey.EncryptedDataKey(keyProviderId:=d64,keyProviderInfo:=d65,ciphertext:=d66);
var d68 : SerializableTypes.ESDKEncryptedDataKeys := [d67];
var d69 : HeaderTypes.ContentType := HeaderTypes.ContentType.Framed;
var d70 : HeaderTypes.HeaderBody := HeaderTypes.HeaderBody.V1HeaderBody(messageType:=d1,esdkSuiteId:=2431,messageId:=d2,encryptionContext:=d63,encryptedDataKeys:=d68,contentType:=d69,headerIvLength:=9454,frameLength:=1734);
var d71 : seq<StandardLibrary.UInt.uint8> := [];
var d72 : SerializableTypes.ESDKEncryptionContext := map[];
var d73 : Aws.Crypto.AlgorithmSuiteId := Crypto.AlgorithmSuiteId.ALG_AES_128_GCM_IV12_TAG16_NO_KDF;
var d74 : AESEncryption.AES_GCM := AESEncryption.AES_GCM.AES_GCM(keyLength:=16,tagLength:=16,ivLength:=12);
var d75 : MaterialProviders.AlgorithmSuites.KeyDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.IDENTITY;
var d76 : MaterialProviders.AlgorithmSuites.CommitmentDerivationAlgorithm := MaterialProviders.AlgorithmSuites.DerivationAlgorithm.None;
var d77 : MaterialProviders.AlgorithmSuites.SignatureAlgorithm := MaterialProviders.AlgorithmSuites.SignatureAlgorithm.None;
var d78 : MaterialProviders.AlgorithmSuites.AlgorithmSuite := MaterialProviders.AlgorithmSuites.AlgorithmSuiteInfo.AlgorithmSuiteInfo(messageVersion:=58,id:=d73,encrypt:=d74,kdf:=d75,commitment:=d76,signature:=d77);
var d79 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d80 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var d81 : HeaderTypes.HeaderAuth := HeaderTypes.HeaderAuth.AESMac(headerIv:=d79,headerAuthTag:=d80);
var d82 : Header.Header := Header.HeaderInfo.HeaderInfo(body:=d70,rawHeader:=d71,encryptionContext:=d72,suite:=d78,headerAuth:=d81);
var d83 : seq<StandardLibrary.UInt.uint8> := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
var r0 := MessageBody.EncryptMessageBody(d0, d82, d83);
}


method {:test} test11() {
var d0 : MessageBody.BodyAADContent := MessageBody.BodyAADContent.AADSingleBlock;
var r0 := MessageBody.BodyAADContentTypeString(d0);
}
method {:test} test13() {
var d0 : MessageBody.BodyAADContent := MessageBody.BodyAADContent.AADFinalFrame;
var r0 := MessageBody.BodyAADContentTypeString(d0);
}

}
