include "../..//src/Crypto/Datatypes.dfy"
module srcCryptoDatatypesdfyUnitTests {
import CryptoDatatypes
// Merging boogie files...
// Converting function calls to method calls...
// Adding Impl$$ methods to support inlining...
// Removing assertions...
// Annotating blocks...
// Generating modifications...

}
