include "../..//src/StandardLibrary/String.dfy"
module srcStandardLibraryStringdfyUnitTests {
import StandardLibrary
import StandardLibrary.String
// Merging boogie files...
// Converting function calls to method calls...
// Adding Impl$$ methods to support inlining...
// Removing assertions...
// Annotating blocks...
// Generating modifications...

}
